# MORA12, SALPRES, VEA y SINMORA

In [1]:
import os
from pathlib import Path

import joblib
import numpy as np
import pandas as pd

In [2]:
data_dir = Path().resolve().parent.parent / "data"
mes_path = 'data-12-2025'
mes_dir = data_dir / mes_path

In [3]:
archivos_en_base = os.listdir(mes_dir)

archivos_credito = [
    f
    for f in archivos_en_base
    if "CREDITO" in f.upper() and f.endswith(".xlsx")
]

archivos_credito

['INFORME INDIVIDUAL DE CARTERA DE CREDITO (MODIFICADO)_ABRIL_2025.xlsx',
 'INFORME INDIVIDUAL DE CARTERA DE CREDITO (MODIFICADO)_AGOSTO_2025.xlsx',
 'INFORME INDIVIDUAL DE CARTERA DE CREDITO (MODIFICADO)_DICIEMBRE_2025.xlsx',
 'INFORME INDIVIDUAL DE CARTERA DE CREDITO (MODIFICADO)_ENERO_2025.xlsx',
 'INFORME INDIVIDUAL DE CARTERA DE CREDITO (MODIFICADO)_FEBRERO_2025.xlsx',
 'INFORME INDIVIDUAL DE CARTERA DE CREDITO (MODIFICADO)_JULIO_2025.xlsx',
 'INFORME INDIVIDUAL DE CARTERA DE CREDITO (MODIFICADO)_JUNIO_2025.xlsx',
 'INFORME INDIVIDUAL DE CARTERA DE CREDITO (MODIFICADO)_MARZO_2025.xlsx',
 'INFORME INDIVIDUAL DE CARTERA DE CREDITO (MODIFICADO)_MAYO_2025.xlsx',
 'INFORME INDIVIDUAL DE CARTERA DE CREDITO (MODIFICADO)_NOVIEMBRE_2025.xlsx',
 'INFORME INDIVIDUAL DE CARTERA DE CREDITO (MODIFICADO)_OCTUBRE_2025.xlsx',
 'INFORME INDIVIDUAL DE CARTERA DE CREDITO (MODIFICADO)_SEPTIEMBRE_2025.xlsx']

In [4]:
dataframes = {}
for archivo in archivos_credito:
    nombre_df = archivo.split(".")[0]
    nombre_df = nombre_df.split("_", maxsplit=1)[1]
    ruta_archivo = mes_dir / archivo
    dataframes[nombre_df] = pd.read_excel(ruta_archivo, header=3)
    print(f"Archivo {archivo} cargado como DataFrame {nombre_df}")

Archivo INFORME INDIVIDUAL DE CARTERA DE CREDITO (MODIFICADO)_ABRIL_2025.xlsx cargado como DataFrame ABRIL_2025
Archivo INFORME INDIVIDUAL DE CARTERA DE CREDITO (MODIFICADO)_AGOSTO_2025.xlsx cargado como DataFrame AGOSTO_2025
Archivo INFORME INDIVIDUAL DE CARTERA DE CREDITO (MODIFICADO)_DICIEMBRE_2025.xlsx cargado como DataFrame DICIEMBRE_2025
Archivo INFORME INDIVIDUAL DE CARTERA DE CREDITO (MODIFICADO)_ENERO_2025.xlsx cargado como DataFrame ENERO_2025
Archivo INFORME INDIVIDUAL DE CARTERA DE CREDITO (MODIFICADO)_FEBRERO_2025.xlsx cargado como DataFrame FEBRERO_2025
Archivo INFORME INDIVIDUAL DE CARTERA DE CREDITO (MODIFICADO)_JULIO_2025.xlsx cargado como DataFrame JULIO_2025
Archivo INFORME INDIVIDUAL DE CARTERA DE CREDITO (MODIFICADO)_JUNIO_2025.xlsx cargado como DataFrame JUNIO_2025
Archivo INFORME INDIVIDUAL DE CARTERA DE CREDITO (MODIFICADO)_MARZO_2025.xlsx cargado como DataFrame MARZO_2025
Archivo INFORME INDIVIDUAL DE CARTERA DE CREDITO (MODIFICADO)_MAYO_2025.xlsx cargado como DataFrame MAYO_2025
Archivo INFORME INDIVIDUAL DE CARTERA DE CREDITO (MODIFICADO)_NOVIEMBRE_2025.xlsx cargado como DataFrame NOVIEMBRE_2025
Archivo INFORME INDIVIDUAL DE CARTERA DE CREDITO (MODIFICADO)_OCTUBRE_2025.xlsx cargado como DataFrame OCTUBRE_2025
Archivo INFORME INDIVIDUAL DE CARTERA DE CREDITO (MODIFICADO)_SEPTIEMBRE_2025.xlsx cargado como DataFrame SEPTIEMBRE_2025

In [5]:
dataframes_credito = dataframes.copy()
dataframes_credito.keys()

dict_keys(['ABRIL_2025', 'AGOSTO_2025', 'DICIEMBRE_2025', 'ENERO_2025', 'FEBRERO_2025', 'JULIO_2025', 'JUNIO_2025', 'MARZO_2025', 'MAYO_2025', 'NOVIEMBRE_2025', 'OCTUBRE_2025', 'SEPTIEMBRE_2025'])

In [6]:
for nombre_df in dataframes_credito.keys():
    dataframes_credito[nombre_df] = dataframes_credito[nombre_df][
        [
            "NIT",
            "NroCredito",
            "CodigoContable",
            "Morosidad",
            "ValorPrestamo",
            "SaldoCapital",
            "SaldoIntereses",
            "OtrosSaldos",
            "clasegarantia",
        ]
    ]
    dataframes_credito[nombre_df] = dataframes_credito[nombre_df].dropna(subset=["NroCredito"])
    dataframes_credito[nombre_df] = dataframes_credito[nombre_df].drop_duplicates(subset=["NroCredito"])
    dataframes_credito[nombre_df] = dataframes_credito[nombre_df].set_index("NroCredito")
    dataframes_credito[nombre_df]["SALPRES"] = (
        dataframes_credito[nombre_df]["SaldoCapital"] / dataframes_credito[nombre_df]["ValorPrestamo"]
    )
    dataframes_credito[nombre_df]["VEA"] = (
        dataframes_credito[nombre_df]["SaldoCapital"]
        + dataframes_credito[nombre_df]["SaldoIntereses"]
        + dataframes_credito[nombre_df]["OtrosSaldos"]
    )

In [7]:
dataframes_credito['DICIEMBRE_2025']

,NIT,CodigoContable,Morosidad,ValorPrestamo,SaldoCapital,SaldoIntereses,OtrosSaldos,clasegarantia,SALPRES,VEA
NroCredito,,,,,,,,,,
002-002-0122632-2,42791041,141105,0,30000000,4341655,12280,0,1.0,0.144722,4353935
002-002-0118009-5,42791041,141105,0,74000000,16710992,5570,0,1.0,0.225824,16716562
004-002-0064765-3,71113904,144205,0,20950000,3050753,595757,0,1.0,0.145621,3646510
004-002-0071007-6,71113904,144205,0,20000000,3284304,4655,0,1.0,0.164215,3288959
006-002-0023761-1,71113904,144205,0,35200000,11443360,19070,0,1.0,0.325095,11462430
...,...,...,...,...,...,...,...,...,...,...
007-002-0001287-6,1036940300,141205,14,5000000,3063704,97890,0,NaN,0.612741,3161594
007-002-0000797-1,98762582,144205,0,6000000,2523727,41160,0,NaN,0.420621,2564887
007-002-0000884-5,43546888,144205,0,17000000,15652913,251280,0,NaN,0.920760,15904193
007-002-0000777-5,1036650236,141205,0,2000000,1242807,20100,0,NaN,0.621403,1262907
007-002-0001211-7,43381938,144205,0,8000000,7774732,125160,0,NaN,0.971842,7899892

In [8]:
dataframes_credito['DICIEMBRE_2025'].info()

<class 'pandas.core.frame.DataFrame'>
Index: 19705 entries, 002-002-0122632-2 to 007-002-0001211-7
Data columns (total 10 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   NIT             19705 non-null  object
 1   CodigoContable  19705 non-null  int64
 2   Morosidad       19705 non-null  int64
 3   ValorPrestamo   19705 non-null  int64
 4   SaldoCapital    19705 non-null  int64
 5   SaldoIntereses  19705 non-null  int64
 6   OtrosSaldos     19705 non-null  int64
 7   clasegarantia   266 non-null    float64
 8   SALPRES         19705 non-null  float64
 9   VEA             19705 non-null  int64
dtypes: float64(2), int64(7), object(1)
memory usage: 1.7+ MB

In [9]:
meses_es = {
    "ENERO": 1,
    "FEBRERO": 2,
    "MARZO": 3,
    "ABRIL": 4,
    "MAYO": 5,
    "JUNIO": 6,
    "JULIO": 7,
    "AGOSTO": 8,
    "SEPTIEMBRE": 9,
    "OCTUBRE": 10,
    "NOVIEMBRE": 11,
    "DICIEMBRE": 12,
}

def mes_ano_to_date(mes_ano):
    mes, ano = mes_ano.split("_")
    return pd.Timestamp(year=int(ano), month=meses_es[mes], day=1)

meses_ordenados = sorted(dataframes.keys(), key=mes_ano_to_date)
meses_ordenados

['ENERO_2025',
 'FEBRERO_2025',
 'MARZO_2025',
 'ABRIL_2025',
 'MAYO_2025',
 'JUNIO_2025',
 'JULIO_2025',
 'AGOSTO_2025',
 'SEPTIEMBRE_2025',
 'OCTUBRE_2025',
 'NOVIEMBRE_2025',
 'DICIEMBRE_2025']

In [10]:
# Fusionar todos los dataframes en uno solo, usando como clave primaria el índice, 
# usando la función merge el método outer, y nombrando cada columna nueva con el nombre 
# del dataframe original

df_mora = dataframes_credito[meses_ordenados[0]][
    ["NIT", "Morosidad", "CodigoContable", "SALPRES", "VEA"]
].copy()
df_mora = df_mora.rename(
    columns={
        "Morosidad": f"Morosidad_{meses_ordenados[0]}",
        "CodigoContable": f"CodigoContable_{meses_ordenados[0]}",
        "NIT": f"NIT_{meses_ordenados[0]}",
        "SALPRES": f"SALPRES_{meses_ordenados[0]}",
        "VEA": f"VEA_{meses_ordenados[0]}",
        "clasegarantia": f"clasegarantia_{meses_ordenados[0]}",
    }
)

for mes in meses_ordenados[1:]:
    df_temp = dataframes_credito[mes][
        ["NIT", "Morosidad", "CodigoContable", "SALPRES", "VEA", "clasegarantia"]
    ].copy()
    df_temp = df_temp.rename(
        columns={
            "Morosidad": f"Morosidad_{mes}",
            "CodigoContable": f"CodigoContable_{mes}",
            "NIT": f"NIT_{mes}",
            "SALPRES": f"SALPRES_{mes}",
            "VEA": f"VEA_{mes}",
            "clasegarantia": f"clasegarantia_{mes}",
        }
    )

    df_mora = df_mora.merge(df_temp, left_index=True, right_index=True, how="outer")
df_mora

,NIT_ENERO_2025,Morosidad_ENERO_2025,CodigoContable_ENERO_2025,SALPRES_ENERO_2025,VEA_ENERO_2025,NIT_FEBRERO_2025,Morosidad_FEBRERO_2025,CodigoContable_FEBRERO_2025,SALPRES_FEBRERO_2025,VEA_FEBRERO_2025,...,CodigoContable_NOVIEMBRE_2025,SALPRES_NOVIEMBRE_2025,VEA_NOVIEMBRE_2025,clasegarantia_NOVIEMBRE_2025,NIT_DICIEMBRE_2025,Morosidad_DICIEMBRE_2025,CodigoContable_DICIEMBRE_2025,SALPRES_DICIEMBRE_2025,VEA_DICIEMBRE_2025,clasegarantia_DICIEMBRE_2025
NroCredito,,,,,,,,,,,,,,,,,,,,,
7,1040039171,0.0,146905.0,0.951044,76083544.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,1036670861,0.0,146930.0,0.918110,6154070.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
007-002-0001464-1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,144205.0,0.988737,10033946.0,1.0,15437544,0.0,144205.0,0.982967,9992119.0,NaN
007-002-0001467-8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,144205.0,0.941430,2869681.0,1.0,43907525,0.0,144205.0,0.919253,2802070.0,1.0
007-002-0001468-7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,144205.0,0.888297,4512527.0,1.0,1036964056,0.0,144205.0,0.870307,4421164.0,NaN
007-002-0001472-1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,141205.0,0.403652,1221398.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN
007-002-0001473-0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,144205.0,0.060000,304032.0,1.0,42880944,0.0,144205.0,0.060000,309072.0,1.0

In [11]:
df_mora.info()

<class 'pandas.core.frame.DataFrame'>
Index: 30270 entries, 7 to 007-002-0001473-0
Data columns (total 71 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   NIT_ENERO_2025                  21502 non-null  object
 1   Morosidad_ENERO_2025            21502 non-null  float64
 2   CodigoContable_ENERO_2025       21502 non-null  float64
 3   SALPRES_ENERO_2025              21502 non-null  float64
 4   VEA_ENERO_2025                  21502 non-null  float64
 5   NIT_FEBRERO_2025                21392 non-null  object
 6   Morosidad_FEBRERO_2025          21392 non-null  float64
 7   CodigoContable_FEBRERO_2025     21392 non-null  float64
 8   SALPRES_FEBRERO_2025            21392 non-null  float64
 9   VEA_FEBRERO_2025                21392 non-null  float64
 10  clasegarantia_FEBRERO_2025      21392 non-null  float64
 11  NIT_MARZO_2025                  21576 non-null  object
 12  Morosidad_MARZO_2025            21576 non-null  float64
 13  CodigoContable_MARZO_2025       21576 non-null  float64
 14  SALPRES_MARZO_2025              21576 non-null  float64
 15  VEA_MARZO_2025                  21576 non-null  float64
 16  clasegarantia_MARZO_2025        21576 non-null  float64
 17  NIT_ABRIL_2025                  21646 non-null  object
 18  Morosidad_ABRIL_2025            21646 non-null  float64
 19  CodigoContable_ABRIL_2025       21646 non-null  float64
 20  SALPRES_ABRIL_2025              21646 non-null  float64
 21  VEA_ABRIL_2025                  21646 non-null  float64
 22  clasegarantia_ABRIL_2025        21646 non-null  float64
 23  NIT_MAYO_2025                   21834 non-null  object
 24  Morosidad_MAYO_2025             21834 non-null  float64
 25  CodigoContable_MAYO_2025        21834 non-null  float64
 26  SALPRES_MAYO_2025               21834 non-null  float64
 27  VEA_MAYO_2025                   21834 non-null  float64
 28  clasegarantia_MAYO_2025         21834 non-null  float64
 29  NIT_JUNIO_2025                  21847 non-null  object
 30  Morosidad_JUNIO_2025            21847 non-null  float64
 31  CodigoContable_JUNIO_2025       21847 non-null  float64
 32  SALPRES_JUNIO_2025              21847 non-null  float64
 33  VEA_JUNIO_2025                  21847 non-null  float64
 34  clasegarantia_JUNIO_2025        21847 non-null  float64
 35  NIT_JULIO_2025                  21505 non-null  object
 36  Morosidad_JULIO_2025            21505 non-null  float64
 37  CodigoContable_JULIO_2025       21505 non-null  float64
 38  SALPRES_JULIO_2025              21505 non-null  float64
 39  VEA_JULIO_2025                  21505 non-null  float64
 40  clasegarantia_JULIO_2025        21505 non-null  float64
 41  NIT_AGOSTO_2025                 21141 non-null  object
 42  Morosidad_AGOSTO_2025           21141 non-null  float64
 43  CodigoContable_AGOSTO_2025      21141 non-null  float64
 44  SALPRES_AGOSTO_2025             21141 non-null  float64
 45  VEA_AGOSTO_2025                 21141 non-null  float64
 46  clasegarantia_AGOSTO_2025       21141 non-null  float64
 47  NIT_SEPTIEMBRE_2025             21020 non-null  object
 48  Morosidad_SEPTIEMBRE_2025       21020 non-null  float64
 49  CodigoContable_SEPTIEMBRE_2025  21020 non-null  float64
 50  SALPRES_SEPTIEMBRE_2025         21020 non-null  float64
 51  VEA_SEPTIEMBRE_2025             21020 non-null  float64
 52  clasegarantia_SEPTIEMBRE_2025   21020 non-null  float64
 53  NIT_OCTUBRE_2025                20364 non-null  object
 54  Morosidad_OCTUBRE_2025          20364 non-null  float64
 55  CodigoContable_OCTUBRE_2025     20364 non-null  float64
 56  SALPRES_OCTUBRE_2025            20364 non-null  float64
 57  VEA_OCTUBRE_2025                20364 non-null  float64
 58  clasegarantia_OCTUBRE_2025      2877 non-null   float64
 59  NIT_NOVIEMBRE_2025              20150 non-null  object
 60  Morosidad_NOVIEMBRE_2025        20150 non-null  float64
 61  CodigoContable_NOVIEMBRE_2025   20150 non-null  float64
 62  SALPRES_NOVIEMBRE_2025          20150 non-null  float64
 63  VEA_NOVIEMBRE_2025              20150 non-null  float64
 64  clasegarantia_NOVIEMBRE_2025    20150 non-null  float64
 65  NIT_DICIEMBRE_2025              19705 non-null  object
 66  Morosidad_DICIEMBRE_2025        19705 non-null  float64
 67  CodigoContable_DICIEMBRE_2025   19705 non-null  float64
 68  SALPRES_DICIEMBRE_2025          19705 non-null  float64
 69  VEA_DICIEMBRE_2025              19705 non-null  float64
 70  clasegarantia_DICIEMBRE_2025    266 non-null    float64
dtypes: float64(59), object(12)
memory usage: 16.6+ MB

In [12]:
# Se eliminan todos los registros que no tienen NIT en el último mes, para que solo 
# queden los créditos vigentes al último mes de los datos
last_month = meses_ordenados[-1]
df_mora = df_mora.dropna(subset=[f"NIT_{last_month}"])
df_mora.info()

<class 'pandas.core.frame.DataFrame'>
Index: 19705 entries, 002-001-0000024-8 to 007-002-0001473-0
Data columns (total 71 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   NIT_ENERO_2025                  12296 non-null  object
 1   Morosidad_ENERO_2025            12296 non-null  float64
 2   CodigoContable_ENERO_2025       12296 non-null  float64
 3   SALPRES_ENERO_2025              12296 non-null  float64
 4   VEA_ENERO_2025                  12296 non-null  float64
 5   NIT_FEBRERO_2025                12916 non-null  object
 6   Morosidad_FEBRERO_2025          12916 non-null  float64
 7   CodigoContable_FEBRERO_2025     12916 non-null  float64
 8   SALPRES_FEBRERO_2025            12916 non-null  float64
 9   VEA_FEBRERO_2025                12916 non-null  float64
 10  clasegarantia_FEBRERO_2025      12916 non-null  float64
 11  NIT_MARZO_2025                  13595 non-null  object
 12  Morosidad_MARZO_2025            13595 non-null  float64
 13  CodigoContable_MARZO_2025       13595 non-null  float64
 14  SALPRES_MARZO_2025              13595 non-null  float64
 15  VEA_MARZO_2025                  13595 non-null  float64
 16  clasegarantia_MARZO_2025        13595 non-null  float64
 17  NIT_ABRIL_2025                  14267 non-null  object
 18  Morosidad_ABRIL_2025            14267 non-null  float64
 19  CodigoContable_ABRIL_2025       14267 non-null  float64
 20  SALPRES_ABRIL_2025              14267 non-null  float64
 21  VEA_ABRIL_2025                  14267 non-null  float64
 22  clasegarantia_ABRIL_2025        14267 non-null  float64
 23  NIT_MAYO_2025                   15075 non-null  object
 24  Morosidad_MAYO_2025             15075 non-null  float64
 25  CodigoContable_MAYO_2025        15075 non-null  float64
 26  SALPRES_MAYO_2025               15075 non-null  float64
 27  VEA_MAYO_2025                   15075 non-null  float64
 28  clasegarantia_MAYO_2025         15075 non-null  float64
 29  NIT_JUNIO_2025                  15730 non-null  object
 30  Morosidad_JUNIO_2025            15730 non-null  float64
 31  CodigoContable_JUNIO_2025       15730 non-null  float64
 32  SALPRES_JUNIO_2025              15730 non-null  float64
 33  VEA_JUNIO_2025                  15730 non-null  float64
 34  clasegarantia_JUNIO_2025        15730 non-null  float64
 35  NIT_JULIO_2025                  16469 non-null  object
 36  Morosidad_JULIO_2025            16469 non-null  float64
 37  CodigoContable_JULIO_2025       16469 non-null  float64
 38  SALPRES_JULIO_2025              16469 non-null  float64
 39  VEA_JULIO_2025                  16469 non-null  float64
 40  clasegarantia_JULIO_2025        16469 non-null  float64
 41  NIT_AGOSTO_2025                 17038 non-null  object
 42  Morosidad_AGOSTO_2025           17038 non-null  float64
 43  CodigoContable_AGOSTO_2025      17038 non-null  float64
 44  SALPRES_AGOSTO_2025             17038 non-null  float64
 45  VEA_AGOSTO_2025                 17038 non-null  float64
 46  clasegarantia_AGOSTO_2025       17038 non-null  float64
 47  NIT_SEPTIEMBRE_2025             17753 non-null  object
 48  Morosidad_SEPTIEMBRE_2025       17753 non-null  float64
 49  CodigoContable_SEPTIEMBRE_2025  17753 non-null  float64
 50  SALPRES_SEPTIEMBRE_2025         17753 non-null  float64
 51  VEA_SEPTIEMBRE_2025             17753 non-null  float64
 52  clasegarantia_SEPTIEMBRE_2025   17753 non-null  float64
 53  NIT_OCTUBRE_2025                18481 non-null  object
 54  Morosidad_OCTUBRE_2025          18481 non-null  float64
 55  CodigoContable_OCTUBRE_2025     18481 non-null  float64
 56  SALPRES_OCTUBRE_2025            18481 non-null  float64
 57  VEA_OCTUBRE_2025                18481 non-null  float64
 58  clasegarantia_OCTUBRE_2025      2562 non-null   float64
 59  NIT_NOVIEMBRE_2025              19092 non-null  object
 60  Morosidad_NOVIEMBRE_2025        19092 non-null  float64
 61  CodigoContable_NOVIEMBRE_2025   19092 non-null  float64
 62  SALPRES_NOVIEMBRE_2025          19092 non-null  float64
 63  VEA_NOVIEMBRE_2025              19092 non-null  float64
 64  clasegarantia_NOVIEMBRE_2025    19092 non-null  float64
 65  NIT_DICIEMBRE_2025              19705 non-null  object
 66  Morosidad_DICIEMBRE_2025        19705 non-null  float64
 67  CodigoContable_DICIEMBRE_2025   19705 non-null  float64
 68  SALPRES_DICIEMBRE_2025          19705 non-null  float64
 69  VEA_DICIEMBRE_2025              19705 non-null  float64
 70  clasegarantia_DICIEMBRE_2025    266 non-null    float64
dtypes: float64(59), object(12)
memory usage: 10.8+ MB

In [13]:
# Crear una columna nueva que sea el valor máximo de morosidad en los últimos 12 meses 
# tomando únicamente las columnas que contienen la palabra "Morosidad"

df_mora[f"MORA12_{meses_ordenados[-1]}"] = df_mora.filter(like="Morosidad").max(
    axis=1, skipna=True
)
df_mora

C:\Users\jhquiza\AppData\Local\Temp\ipykernel_33140\2367264811.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_mora[f"MORA12_{meses_ordenados[-1]}"] = df_mora.filter(like="Morosidad").max(

,NIT_ENERO_2025,Morosidad_ENERO_2025,CodigoContable_ENERO_2025,SALPRES_ENERO_2025,VEA_ENERO_2025,NIT_FEBRERO_2025,Morosidad_FEBRERO_2025,CodigoContable_FEBRERO_2025,SALPRES_FEBRERO_2025,VEA_FEBRERO_2025,...,SALPRES_NOVIEMBRE_2025,VEA_NOVIEMBRE_2025,clasegarantia_NOVIEMBRE_2025,NIT_DICIEMBRE_2025,Morosidad_DICIEMBRE_2025,CodigoContable_DICIEMBRE_2025,SALPRES_DICIEMBRE_2025,VEA_DICIEMBRE_2025,clasegarantia_DICIEMBRE_2025,MORA12_DICIEMBRE_2025
NroCredito,,,,,,,,,,,,,,,,,,,,,
002-001-0000024-8,901-285-696-7,0.0,146205.0,0.393582,1.972239e+07,901-285-696-7,0.0,146515.0,0.375200,1.879441e+07,...,0.218958,1.110446e+07,1.0,901-285-696-7,0.0,146205.0,0.201480,1.008140e+07,NaN,0.0
002-001-0000026-6,900-698-421-8,38.0,146210.0,0.627775,6.461706e+07,900-698-421-8,36.0,146520.0,0.611830,6.294684e+07,...,0.489768,4.932788e+07,1.0,900-698-421-8,16.0,146515.0,0.476578,4.861521e+07,NaN,38.0
002-001-0000027-5,811-021-864-9,0.0,146205.0,0.758204,1.785100e+09,811-021-864-9,0.0,146515.0,0.749550,1.761914e+09,...,0.665610,1.581399e+09,1.0,811-021-864-9,0.0,146515.0,0.642260,1.510919e+09,NaN,6.0
002-001-0000028-4,900-409-773-7,5.0,146205.0,0.641627,1.306258e+08,900-409-773-7,3.0,146515.0,0.625858,1.274151e+08,...,0.472855,9.549693e+07,1.0,900-409-773-7,5.0,146515.0,0.454555,9.191729e+07,NaN,35.0
002-001-0000029-3,901-406-831-6,1.0,146205.0,0.875484,6.366050e+08,901-406-831-6,0.0,146515.0,0.875484,6.441069e+08,...,0.848534,6.309995e+08,1.0,901-406-831-6,181.0,146535.0,0.848534,6.309995e+08,NaN,181.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
007-002-0001463-2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.847514,8.600510e+05,1.0,1035912774,14.0,144205.0,0.847514,8.732510e+05,1.0,74.0
007-002-0001464-1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.988737,1.003395e+07,1.0,15437544,0.0,144205.0,0.982967,9.992119e+06,NaN,0.0
007-002-0001467-8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.941430,2.869681e+06,1.0,43907525,0.0,144205.0,0.919253,2.802070e+06,1.0,0.0
007-002-0001468-7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.888297,4.512527e+06,1.0,1036964056,0.0,144205.0,0.870307,4.421164e+06,NaN,14.0
007-002-0001473-0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.060000,3.040320e+05,1.0,42880944,0.0,144205.0,0.060000,3.090720e+05,1.0,0.0

In [14]:
# Conservar solo las columnas que contienen el último mes
columnas_a_conservar = [
    f"Morosidad_{meses_ordenados[-1]}",
    f"CodigoContable_{meses_ordenados[-1]}",
    f"NIT_{meses_ordenados[-1]}",
    f"SALPRES_{meses_ordenados[-1]}",
    f"VEA_{meses_ordenados[-1]}",
    f"MORA12_{meses_ordenados[-1]}",
    f"clasegarantia_{meses_ordenados[-1]}",
]

df_mora = df_mora[columnas_a_conservar]
df_mora

,Morosidad_DICIEMBRE_2025,CodigoContable_DICIEMBRE_2025,NIT_DICIEMBRE_2025,SALPRES_DICIEMBRE_2025,VEA_DICIEMBRE_2025,MORA12_DICIEMBRE_2025,clasegarantia_DICIEMBRE_2025
NroCredito,,,,,,,
002-001-0000024-8,0.0,146205.0,901-285-696-7,0.201480,1.008140e+07,0.0,NaN
002-001-0000026-6,16.0,146515.0,900-698-421-8,0.476578,4.861521e+07,38.0,NaN
002-001-0000027-5,0.0,146515.0,811-021-864-9,0.642260,1.510919e+09,6.0,NaN
002-001-0000028-4,5.0,146515.0,900-409-773-7,0.454555,9.191729e+07,35.0,NaN
002-001-0000029-3,181.0,146535.0,901-406-831-6,0.848534,6.309995e+08,181.0,NaN
...,...,...,...,...,...,...,...
007-002-0001463-2,14.0,144205.0,1035912774,0.847514,8.732510e+05,74.0,1.0
007-002-0001464-1,0.0,144205.0,15437544,0.982967,9.992119e+06,0.0,NaN
007-002-0001467-8,0.0,144205.0,43907525,0.919253,2.802070e+06,0.0,1.0
007-002-0001468-7,0.0,144205.0,1036964056,0.870307,4.421164e+06,14.0,NaN
007-002-0001473-0,0.0,144205.0,42880944,0.060000,3.090720e+05,0.0,1.0

In [15]:
df_mora.info()

<class 'pandas.core.frame.DataFrame'>
Index: 19705 entries, 002-001-0000024-8 to 007-002-0001473-0
Data columns (total 7 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   Morosidad_DICIEMBRE_2025       19705 non-null  float64
 1   CodigoContable_DICIEMBRE_2025  19705 non-null  float64
 2   NIT_DICIEMBRE_2025             19705 non-null  object
 3   SALPRES_DICIEMBRE_2025         19705 non-null  float64
 4   VEA_DICIEMBRE_2025             19705 non-null  float64
 5   MORA12_DICIEMBRE_2025          19705 non-null  float64
 6   clasegarantia_DICIEMBRE_2025   266 non-null    float64
dtypes: float64(6), object(1)
memory usage: 1.2+ MB

In [16]:
# Quitar el mes y el año de los nombres de las columnas
new_column_names = {
    f"Morosidad_{meses_ordenados[-1]}": "Morosidad",
    f"CodigoContable_{meses_ordenados[-1]}": "CodigoContable",
    f"NIT_{meses_ordenados[-1]}": "NIT",
    f"SALPRES_{meses_ordenados[-1]}": "SALPRES",
    f"VEA_{meses_ordenados[-1]}": "VEA",
    f"MORA12_{meses_ordenados[-1]}": "MORA12",
    f"clasegarantia_{meses_ordenados[-1]}": "clasegarantia",
}

df_mora = df_mora.rename(columns=new_column_names)
df_mora = df_mora.reset_index()
df_mora["SINMORA"] = np.where(df_mora["MORA12"] == 0, 1, 0)
df_mora

,NroCredito,Morosidad,CodigoContable,NIT,SALPRES,VEA,MORA12,clasegarantia,SINMORA
0,002-001-0000024-8,0.0,146205.0,901-285-696-7,0.201480,1.008140e+07,0.0,NaN,1
1,002-001-0000026-6,16.0,146515.0,900-698-421-8,0.476578,4.861521e+07,38.0,NaN,0
2,002-001-0000027-5,0.0,146515.0,811-021-864-9,0.642260,1.510919e+09,6.0,NaN,0
3,002-001-0000028-4,5.0,146515.0,900-409-773-7,0.454555,9.191729e+07,35.0,NaN,0
4,002-001-0000029-3,181.0,146535.0,901-406-831-6,0.848534,6.309995e+08,181.0,NaN,0
...,...,...,...,...,...,...,...,...,...
19700,007-002-0001463-2,14.0,144205.0,1035912774,0.847514,8.732510e+05,74.0,1.0,0
19701,007-002-0001464-1,0.0,144205.0,15437544,0.982967,9.992119e+06,0.0,NaN,1
19702,007-002-0001467-8,0.0,144205.0,43907525,0.919253,2.802070e+06,0.0,1.0,1
19703,007-002-0001468-7,0.0,144205.0,1036964056,0.870307,4.421164e+06,14.0,NaN,0
19704,007-002-0001473-0,0.0,144205.0,42880944,0.060000,3.090720e+05,0.0,1.0,1

In [17]:
# Crear una nueva columna llamada PDI que se calcula así:
# Si clasegarantia es igual a 1 o a 4, entonces:
#  Si Morosidad >= 420, PDI = 1.0,
#  Si Morosidad < 420 y Morosidad >= 210, PDI = 0.7,
#  Si Morosidad < 210, PDI = 0.6,
#  Si Morosidad < 90, PDI = 0.45,


# Si clasegarantia es igual a 2, entonces:
#  Si Morosidad >= 720, PDI = 1.0,
#  Si Morosidad < 720 y Morosidad >= 360, PDI = 0.7,
#  Si Morosidad < 360, PDI = 0.4,
# Si clasegarantia es igual a 3, entonces:
#  Si Morosidad >= 540, PDI = 1.0,
#  Si Morosidad < 540 y Morosidad >= 270, PDI = 0.7,
#  Si Morosidad < 270, PDI = 0.5


def calcular_pdi(row):
    clase = row["clasegarantia"]
    morosidad = row["Morosidad"]

    if clase in [1, 4, 6]:
        if morosidad >= 420:
            return 1.0
        elif morosidad >= 210:
            return 0.7
        elif morosidad >= 90:
            return 0.6
        else:
            return 0.45
    elif clase == 2:
        if morosidad >= 720:
            return 1.0
        elif morosidad >= 360:
            return 0.7
        else:
            return 0.4
    elif clase == 3:
        if morosidad >= 540:
            return 1.0
        elif morosidad >= 270:
            return 0.7
        else:
            return 0.5
    else:
        return np.nan


df_mora["PDI"] = df_mora.apply(calcular_pdi, axis=1)
df_mora

,NroCredito,Morosidad,CodigoContable,NIT,SALPRES,VEA,MORA12,clasegarantia,SINMORA,PDI
0,002-001-0000024-8,0.0,146205.0,901-285-696-7,0.201480,1.008140e+07,0.0,NaN,1,NaN
1,002-001-0000026-6,16.0,146515.0,900-698-421-8,0.476578,4.861521e+07,38.0,NaN,0,NaN
2,002-001-0000027-5,0.0,146515.0,811-021-864-9,0.642260,1.510919e+09,6.0,NaN,0,NaN
3,002-001-0000028-4,5.0,146515.0,900-409-773-7,0.454555,9.191729e+07,35.0,NaN,0,NaN
4,002-001-0000029-3,181.0,146535.0,901-406-831-6,0.848534,6.309995e+08,181.0,NaN,0,NaN
...,...,...,...,...,...,...,...,...,...,...
19700,007-002-0001463-2,14.0,144205.0,1035912774,0.847514,8.732510e+05,74.0,1.0,0,0.45
19701,007-002-0001464-1,0.0,144205.0,15437544,0.982967,9.992119e+06,0.0,NaN,1,NaN
19702,007-002-0001467-8,0.0,144205.0,43907525,0.919253,2.802070e+06,0.0,1.0,1,0.45
19703,007-002-0001468-7,0.0,144205.0,1036964056,0.870307,4.421164e+06,14.0,NaN,0,NaN
19704,007-002-0001473-0,0.0,144205.0,42880944,0.060000,3.090720e+05,0.0,1.0,1,0.45

# Antiguedad (ANTI) y Activo

In [19]:
archivos_asociados = [
    f
    for f in archivos_en_base
    if "ASOCIADOS" in f.upper() and f.endswith(".xlsx")
]

archivos_asociados

['INFORME ASOCIADOS_DICIEMBRE_2025.xlsx']

In [21]:
# Cargar el archivo 'Archivos originales/INFORME ASOCIADOS_JUNIO_2022.xlsx' en un dataframe llamado 'vinculacion_{mes_año}' donde {mes_año} está extraído del nombre del archivo
#data_dir = get_data_path("data/data-09-2025")
mes_anno = archivos_asociados[0].split(".")[0]
mes_anno = mes_anno.split("_", maxsplit=1)[1]
archivo = mes_dir / archivos_asociados[0]
mes_anno

'DICIEMBRE_2025'

In [22]:
nombre_df = f"vinculacion_{mes_anno}"
vinculaciones = {}
vinculaciones[nombre_df] = pd.read_excel(archivo, header=3)

vinculaciones[nombre_df]["Fecha de ingreso"] = pd.to_datetime(
    vinculaciones[nombre_df]["Fecha de ingreso"], errors="coerce", format="%d/%m/%Y"
)
vinculaciones[nombre_df]["Activo"] = (
    vinculaciones[nombre_df]["Activo"].fillna(1).astype(int)
)
vinculaciones[nombre_df].info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 49846 entries, 0 to 49845
Data columns (total 5 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Número de identificación  49846 non-null  object
 1   Nombres                   49846 non-null  object
 2   Primer apellido           49531 non-null  object
 3   Activo                    49846 non-null  int64
 4   Fecha de ingreso          49846 non-null  datetime64[ns]
dtypes: datetime64[ns](1), int64(1), object(3)
memory usage: 1.9+ MB

In [23]:
# Crear una columna nueva llamada 'Activo desde' que contenga el número de días que lleva activo el cliente desde la fecha de ingreso hasta el último día del mes que orresponde a la variable mes_anno. Si 'Activo' es 0 o Nan, entonces esta variable también será 0
ultimo_dia_mes = mes_ano_to_date(mes_anno) + pd.offsets.MonthEnd(0)
vinculaciones[nombre_df]["ANTI"] = (
    vinculaciones[nombre_df]["Activo"]
    * (ultimo_dia_mes - vinculaciones[nombre_df]["Fecha de ingreso"]).dt.days
)
vinculaciones[nombre_df]

,Número de identificación,Nombres,Primer apellido,Activo,Fecha de ingreso,ANTI
0,96055,Felix Antonio,Castaño,1,2002-05-18,8628
1,152419,Jacques,Fournier,1,2012-02-24,5059
2,179810,Edwin,Arenas,1,2015-12-15,3669
3,204414,Lina Zulema,Pedrazas,1,2019-01-28,2529
4,219552,German Rodrigo,Tenelanda,1,2002-05-25,8621
...,...,...,...,...,...,...
49841,901-792-877-8,Inversiones Saint Polito Sas,NaN,1,2024-02-21,679
49842,1-037-614-537-4,Villegas Tobon Leidy Johana,NaN,1,2022-08-03,1246
49843,825276723041978,Katerine Del Valle,Hernandez,1,2021-06-30,1645
49844,924835703011983,Gabriel Eduardo,Joaquim,1,2020-02-01,2160
49845,938711918091996,Alba Carolina,Urbina,1,2021-09-23,1560

In [24]:
# Fusionar el dataframe df_mora con el dataframe vinculaciones[nombre_df] usando como clave primaria la columna 'NIT' de df_mora y la columna 'Número de identificación' de vinculaciones[nombre_df], usando el método left
df_features = pd.merge(
    df_mora[
        [
            "NroCredito",
            "NIT",
            "CodigoContable",
            "SALPRES",
            "VEA",
            "MORA12",
            "SINMORA",
            "Morosidad",
            "clasegarantia",
            "PDI",
        ]
    ],
    vinculaciones[nombre_df][["Número de identificación", "Activo", "ANTI"]],
    left_on="NIT",
    right_on="Número de identificación",
    how="left",
)

df_features = df_features.drop(columns=["Número de identificación"])
df_features

,NroCredito,NIT,CodigoContable,SALPRES,VEA,MORA12,SINMORA,Morosidad,clasegarantia,PDI,Activo,ANTI
0,002-001-0000024-8,901-285-696-7,146205.0,0.201480,1.008140e+07,0.0,1,0.0,NaN,NaN,1.0,1540.0
1,002-001-0000026-6,900-698-421-8,146515.0,0.476578,4.861521e+07,38.0,0,16.0,NaN,NaN,1.0,1273.0
2,002-001-0000027-5,811-021-864-9,146515.0,0.642260,1.510919e+09,6.0,0,0.0,NaN,NaN,1.0,1883.0
3,002-001-0000028-4,900-409-773-7,146515.0,0.454555,9.191729e+07,35.0,0,5.0,NaN,NaN,1.0,1233.0
4,002-001-0000029-3,901-406-831-6,146535.0,0.848534,6.309995e+08,181.0,0,181.0,NaN,NaN,1.0,1223.0
...,...,...,...,...,...,...,...,...,...,...,...,...
19700,007-002-0001463-2,1035912774,144205.0,0.847514,8.732510e+05,74.0,0,14.0,1.0,0.45,1.0,1549.0
19701,007-002-0001464-1,15437544,144205.0,0.982967,9.992119e+06,0.0,1,0.0,NaN,NaN,1.0,6497.0
19702,007-002-0001467-8,43907525,144205.0,0.919253,2.802070e+06,0.0,1,0.0,1.0,0.45,1.0,555.0
19703,007-002-0001468-7,1036964056,144205.0,0.870307,4.421164e+06,14.0,0,0.0,NaN,NaN,1.0,656.0
19704,007-002-0001473-0,42880944,144205.0,0.060000,3.090720e+05,0.0,1,0.0,1.0,0.45,1.0,181.0

# Aportes (AP)

In [25]:
archivos_aportes = [
    f
    for f in archivos_en_base
    if "APORTES" in f.upper() and f.endswith(".xlsx")
]

archivos_aportes

['INFORME INDIVIDUAL DE APORTES_DICIEMBRE_2025.xlsx']

In [27]:
#archivo = data_dir / "INFORME INDIVIDUAL DE APORTES_SEPTIEMBRE_2025.xlsx"
nombre_df = f"aporte_{mes_anno}"
aportes = {}
aportes[nombre_df] = pd.read_excel(mes_dir / archivos_aportes[0], header=3)

aportes[nombre_df]["Aporte/Contribución Ordinario"] = aportes[nombre_df][
    "Aporte/Contribución Ordinario"
].fillna(0)
aportes[nombre_df] = aportes[nombre_df].rename(
    columns={"Aporte/Contribución Ordinario": "AP"}
)
aportes[nombre_df].info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 46530 entries, 0 to 46529
Data columns (total 9 columns):
 #   Column                              Non-Null Count  Dtype
---  ------                              --------------  -----
 0   Tipo identificación                 46530 non-null  object
 1   Número de identificación            46530 non-null  int64
 2   Saldo a fecha                       46530 non-null  float64
 3   Valor Aporte/Contribución Mensual   46530 non-null  int64
 4   AP                                  46530 non-null  float64
 5   Aporte/Contribución ExtraOrdinario  46530 non-null  int64
 6   ValorRevalorizacion                 46530 non-null  int64
 7   Monto Promedio                      46530 non-null  int64
 8   UltimaFecha                         46530 non-null  datetime64[ns]
dtypes: datetime64[ns](1), float64(2), int64(5), object(1)
memory usage: 3.2+ MB

In [28]:
# Fusionar el dataframe df_features con el dataframe aportes[nombre_df] usando como clave primaria la columna 'NIT' de df_features y la columna 'Número de identificación' de aportes[nombre_df], usando el método left
df_features = pd.merge(
    df_features,
    aportes[nombre_df][["Número de identificación", "AP"]],
    left_on="NIT",
    right_on="Número de identificación",
    how="left",
)

df_features = df_features.drop(columns=["Número de identificación"])
df_features

,NroCredito,NIT,CodigoContable,SALPRES,VEA,MORA12,SINMORA,Morosidad,clasegarantia,PDI,Activo,ANTI,AP
0,002-001-0000024-8,901-285-696-7,146205.0,0.201480,1.008140e+07,0.0,1,0.0,NaN,NaN,1.0,1540.0,NaN
1,002-001-0000026-6,900-698-421-8,146515.0,0.476578,4.861521e+07,38.0,0,16.0,NaN,NaN,1.0,1273.0,NaN
2,002-001-0000027-5,811-021-864-9,146515.0,0.642260,1.510919e+09,6.0,0,0.0,NaN,NaN,1.0,1883.0,NaN
3,002-001-0000028-4,900-409-773-7,146515.0,0.454555,9.191729e+07,35.0,0,5.0,NaN,NaN,1.0,1233.0,NaN
4,002-001-0000029-3,901-406-831-6,146535.0,0.848534,6.309995e+08,181.0,0,181.0,NaN,NaN,1.0,1223.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
19700,007-002-0001463-2,1035912774,144205.0,0.847514,8.732510e+05,74.0,0,14.0,1.0,0.45,1.0,1549.0,2490721.0
19701,007-002-0001464-1,15437544,144205.0,0.982967,9.992119e+06,0.0,1,0.0,NaN,NaN,1.0,6497.0,2370054.0
19702,007-002-0001467-8,43907525,144205.0,0.919253,2.802070e+06,0.0,1,0.0,1.0,0.45,1.0,555.0,925001.0
19703,007-002-0001468-7,1036964056,144205.0,0.870307,4.421164e+06,14.0,0,0.0,NaN,NaN,1.0,656.0,1107001.0
19704,007-002-0001473-0,42880944,144205.0,0.060000,3.090720e+05,0.0,1,0.0,1.0,0.45,1.0,181.0,420001.0

# Ahorro CDAT (COOCDAT)

In [29]:
archivos_cdat = [
    f
    for f in archivos_en_base
    if "CAPTACIONES" in f.upper() and f.endswith(".xlsx")
]

archivos_cdat

['INFORME INDIVIDUAL DE LAS CAPTACIONES (MODIFICADO)_DICIEMBRE_2025.xlsx']

In [30]:
#archivo = (
#    data_dir / "INFORME INDIVIDUAL DE LAS CAPTACIONES (MODIFICADO)_SEPTIEMBRE_2025.xlsx"
#)

nombre_df = f"captacion_{mes_anno}"
captaciones = {}
captaciones[nombre_df] = pd.read_excel(mes_dir / archivos_cdat[0], header=3)

captaciones[nombre_df].info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 52183 entries, 0 to 52182
Data columns (total 22 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   TipoIden             52183 non-null  object
 1   NIT                  52183 non-null  object
 2   CodigoContable       52183 non-null  int64
 3   NombreDeposito       52183 non-null  object
 4   TipoAhorro           52183 non-null  int64
 5   Amortizacion         52183 non-null  int64
 6   FechaApertura        52183 non-null  datetime64[ns]
 7   Plazo                52183 non-null  int64
 8   FechaVencimiento     26733 non-null  datetime64[ns]
 9   Modalidad            52183 non-null  int64
 10  TasaInteresNominal   52183 non-null  float64
 11  TasaInteresEfectiva  52183 non-null  float64
 12  InteresesCausados    52183 non-null  int64
 13  Saldo                52183 non-null  float64
 14  DepositoInicial      52183 non-null  float64
 15  NumeroCuenta         52183 non-null  int64
 16  excentagmf           52183 non-null  int64
 17  fechaaceptacionegmf  1027 non-null   datetime64[ns]
 18  Estado               52183 non-null  int64
 19  CtaBajoMonto         52183 non-null  int64
 20  Cotitulares          52183 non-null  int64
 21  ConjuntaColectivo    0 non-null      float64
dtypes: datetime64[ns](3), float64(5), int64(11), object(3)
memory usage: 8.8+ MB

In [31]:
# Crear una columna llamada 'es CDAT' que sea igual a 1 si la columna 'NombreDeposito' contiene la palabra 'CDAT' y 0 en caso contrario
captaciones[nombre_df]["es CDAT"] = (
    captaciones[nombre_df]["NombreDeposito"]
    .str.contains("CDAT", case=False, na=False)
    .astype(int)
)
captaciones[nombre_df]["COOCDAT"] = (
    captaciones[nombre_df]["es CDAT"] * captaciones[nombre_df]["Saldo"]
)
captaciones[nombre_df] = captaciones[nombre_df][captaciones[nombre_df]["es CDAT"] == 1]
captaciones[nombre_df] = captaciones[nombre_df][["NIT", "COOCDAT"]]

# Agrupar por NIT y sumar COOCDAT
captaciones[nombre_df] = captaciones[nombre_df].groupby("NIT").sum().reset_index()
# Mostrar la información del dataframe
captaciones[nombre_df].info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4000 entries, 0 to 3999
Data columns (total 2 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   NIT      4000 non-null   object
 1   COOCDAT  4000 non-null   float64
dtypes: float64(1), object(1)
memory usage: 62.6+ KB

In [32]:
captaciones[nombre_df] = captaciones[nombre_df].rename(columns={"NIT": "NIT_1"})
df_all_features = pd.merge(
    df_features, captaciones[nombre_df], left_on="NIT", right_on="NIT_1", how="left"
)

df_all_features = df_all_features.drop(columns=["NIT_1"])
df_all_features

,NroCredito,NIT,CodigoContable,SALPRES,VEA,MORA12,SINMORA,Morosidad,clasegarantia,PDI,Activo,ANTI,AP,COOCDAT
0,002-001-0000024-8,901-285-696-7,146205.0,0.201480,1.008140e+07,0.0,1,0.0,NaN,NaN,1.0,1540.0,NaN,NaN
1,002-001-0000026-6,900-698-421-8,146515.0,0.476578,4.861521e+07,38.0,0,16.0,NaN,NaN,1.0,1273.0,NaN,NaN
2,002-001-0000027-5,811-021-864-9,146515.0,0.642260,1.510919e+09,6.0,0,0.0,NaN,NaN,1.0,1883.0,NaN,NaN
3,002-001-0000028-4,900-409-773-7,146515.0,0.454555,9.191729e+07,35.0,0,5.0,NaN,NaN,1.0,1233.0,NaN,NaN
4,002-001-0000029-3,901-406-831-6,146535.0,0.848534,6.309995e+08,181.0,0,181.0,NaN,NaN,1.0,1223.0,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19700,007-002-0001463-2,1035912774,144205.0,0.847514,8.732510e+05,74.0,0,14.0,1.0,0.45,1.0,1549.0,2490721.0,NaN
19701,007-002-0001464-1,15437544,144205.0,0.982967,9.992119e+06,0.0,1,0.0,NaN,NaN,1.0,6497.0,2370054.0,NaN
19702,007-002-0001467-8,43907525,144205.0,0.919253,2.802070e+06,0.0,1,0.0,1.0,0.45,1.0,555.0,925001.0,NaN
19703,007-002-0001468-7,1036964056,144205.0,0.870307,4.421164e+06,14.0,0,0.0,NaN,NaN,1.0,656.0,1107001.0,NaN
19704,007-002-0001473-0,42880944,144205.0,0.060000,3.090720e+05,0.0,1,0.0,1.0,0.45,1.0,181.0,420001.0,NaN

In [33]:
df_all_features.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 19705 entries, 0 to 19704
Data columns (total 14 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   NroCredito      19705 non-null  object
 1   NIT             19705 non-null  object
 2   CodigoContable  19705 non-null  float64
 3   SALPRES         19705 non-null  float64
 4   VEA             19705 non-null  float64
 5   MORA12          19705 non-null  float64
 6   SINMORA         19705 non-null  int64
 7   Morosidad       19705 non-null  float64
 8   clasegarantia   266 non-null    float64
 9   PDI             266 non-null    float64
 10  Activo          19702 non-null  float64
 11  ANTI            19702 non-null  float64
 12  AP              18872 non-null  float64
 13  COOCDAT         627 non-null    float64
dtypes: float64(11), int64(1), object(2)
memory usage: 2.1+ MB

# Estimaciones de calificación crédito con libranza y sin libranza

In [34]:
cod_con_libranza = [
    141100,
    141110,
    141115,
    141120,
    141125,
    144100,
    144110,
    144115,
    144120,
    144125,
    146930,
    146935,
    146940,
    146945,
    146950,
]

cod_sin_libranza = [
    141200,
    141210,
    141215,
    141220,
    141225,
    144200,
    144210,
    144215,
    144220,
    144225,
]

In [35]:
df_con_libranza = df_all_features[
    df_all_features["CodigoContable"].isin(cod_con_libranza)
].copy()
df_con_libranza.info()

<class 'pandas.core.frame.DataFrame'>
Index: 73 entries, 409 to 18405
Data columns (total 14 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   NroCredito      73 non-null     object
 1   NIT             73 non-null     object
 2   CodigoContable  73 non-null     float64
 3   SALPRES         73 non-null     float64
 4   VEA             73 non-null     float64
 5   MORA12          73 non-null     float64
 6   SINMORA         73 non-null     int64
 7   Morosidad       73 non-null     float64
 8   clasegarantia   0 non-null      float64
 9   PDI             0 non-null      float64
 10  Activo          73 non-null     float64
 11  ANTI            73 non-null     float64
 12  AP              73 non-null     float64
 13  COOCDAT         0 non-null      float64
dtypes: float64(11), int64(1), object(2)
memory usage: 8.6+ KB

In [36]:
df_con_libranza["COOCDAT"] = df_con_libranza["COOCDAT"].fillna(0)
df_con_libranza = df_con_libranza[df_con_libranza["Activo"] == 1]
df_con_libranza["AP"] = df_con_libranza["AP"].fillna(0)
df_con_libranza.info()

<class 'pandas.core.frame.DataFrame'>
Index: 73 entries, 409 to 18405
Data columns (total 14 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   NroCredito      73 non-null     object
 1   NIT             73 non-null     object
 2   CodigoContable  73 non-null     float64
 3   SALPRES         73 non-null     float64
 4   VEA             73 non-null     float64
 5   MORA12          73 non-null     float64
 6   SINMORA         73 non-null     int64
 7   Morosidad       73 non-null     float64
 8   clasegarantia   0 non-null      float64
 9   PDI             0 non-null      float64
 10  Activo          73 non-null     float64
 11  ANTI            73 non-null     float64
 12  AP              73 non-null     float64
 13  COOCDAT         73 non-null     float64
dtypes: float64(11), int64(1), object(2)
memory usage: 8.6+ KB

In [37]:
def get_models_path(relative_path: str = "") -> Path:
    """Retorna la ruta absoluta a la carpeta de modelos compartida."""
    # Busca la raíz del repositorio basándose en este archivo (src/config.py)
    root = Path.cwd().parent
    models_dir = root / relative_path

    if not models_dir.exists():
        os.makedirs(models_dir)

    return models_dir

In [38]:
# Cargar modelo 'lgbm_model_con_libranza.pkl' y crear en el dataframe 'df_con_libranza' una columna llamada Z con las predicciones del modelo
models_dir = get_models_path("models")
vars_con_libranza = ["AP", "COOCDAT", "MORA12", "SINMORA", "ANTI"]
lgbm_model_con_libranza = joblib.load(models_dir / "lightgbm_con_libranza.joblib")
df_con_libranza["Calif.modelo"] = lgbm_model_con_libranza.predict(
    df_con_libranza[vars_con_libranza]
)
df_con_libranza

c:\Users\jhquiza\repos\proyecto-riesgos\.venv\Lib\site-packages\sklearn\base.py:442: InconsistentVersionWarning: Trying to unpickle estimator DecisionTreeClassifier from version 1.8.0 when using version 1.7.2. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:
https://scikit-learn.org/stable/model_persistence.html#security-maintainability-limitations
  warnings.warn(

,NroCredito,NIT,CodigoContable,SALPRES,VEA,MORA12,SINMORA,Morosidad,clasegarantia,PDI,Activo,ANTI,AP,COOCDAT,Calif.modelo
409,002-002-0119592-6,15508251,141110.0,0.001944,23179.0,33.0,0,33.0,NaN,NaN,1.0,9982.0,6630767.0,0.0,1
478,002-002-0120768-2,43557644,144125.0,0.454133,19608451.0,0.0,1,0.0,NaN,NaN,1.0,3254.0,6480001.0,0.0,0
788,002-002-0125077-7,42789870,141110.0,0.005368,54339.0,41.0,0,41.0,NaN,NaN,1.0,2321.0,3035205.0,0.0,1
1233,002-002-0128853-1,8461117,144125.0,0.537680,10846461.0,0.0,1,0.0,NaN,NaN,1.0,4411.0,1584877.0,0.0,0
1263,002-002-0129255-3,1039623661,144110.0,0.696457,18689349.0,31.0,0,31.0,NaN,NaN,1.0,3619.0,1664223.0,0.0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17584,006-002-0032251-9,1045735821,144120.0,0.852780,11246995.0,0.0,1,0.0,NaN,NaN,1.0,3332.0,671327.0,0.0,0
17722,006-002-0032804-1,1007321384,144125.0,0.612451,1855660.0,0.0,1,0.0,NaN,NaN,1.0,882.0,799132.0,0.0,0
17886,006-002-0033378-5,43989143,144110.0,0.412673,1255057.0,0.0,1,0.0,NaN,NaN,1.0,1124.0,1063201.0,0.0,0
18356,006-002-0034788-7,70567161,144110.0,0.704429,1839090.0,42.0,0,42.0,NaN,NaN,1.0,2128.0,1750460.0,0.0,1
18405,006-002-0034901-9,1033340571,144110.0,0.612033,1908791.0,93.0,0,33.0,NaN,NaN,1.0,284.0,258533.0,0.0,2

In [39]:
df_con_libranza["MORA12"].describe()

count     73.000000
mean      66.219178
std      102.914777
min        0.000000
25%        0.000000
50%       35.000000
75%       61.000000
max      631.000000
Name: MORA12, dtype: float64

In [40]:
df_con_libranza["Calif.modelo"].value_counts()

Calif.modelo
1    36
0    20
2    17
Name: count, dtype: int64

In [41]:
df_con_libranza["Calif.modelo"] = df_con_libranza["Calif.modelo"].map(
    {0: "A", 1: "B", 2: "C", 3: "D"}
)

In [42]:
# Crear columna 'Calif.homologada', que se calcula así:
# Si 'Calif.modelo' es A, entonces 'Calif.homologada' es A
# Si 'Calif.modelo' es B, y 'MORA12' es menor o igual a 30, entonces 'Calif.homologada' es A
# Si 'Calif.modelo' es B, y 'MORA12' es mayor a 30, entonces 'Calif.homologada' es B
# Si 'Calif.modelo' es C, y 'MORA12' es menor o igual a 30, entonces 'Calif.homologada' es B
# Si 'Calif.modelo' es C, y 'MORA12' es mayor a 30, entonces 'Calif.homologada' es C
# Si 'Calif.modelo' es D o E, entonces 'Calif.homologada' es C
# Si 'MORA12' es mayor o igual a 90, y menor o igual a 180, entonces 'Calif.homologada' es D
# Si 'MORA12' es mayor a 180, entonces 'Calif.homologada' es E

condiciones = [
    (df_con_libranza["Calif.modelo"] == "A"),
    (df_con_libranza["Calif.modelo"] == "B") & (df_con_libranza["MORA12"] <= 30),
    (df_con_libranza["Calif.modelo"] == "B")
    & (df_con_libranza["MORA12"] > 30)
    & (df_con_libranza["MORA12"] < 90),
    (df_con_libranza["Calif.modelo"] == "C") & (df_con_libranza["MORA12"] <= 30),
    (df_con_libranza["Calif.modelo"] == "C")
    & (df_con_libranza["MORA12"] > 30)
    & (df_con_libranza["MORA12"] < 90),
    (df_con_libranza["Calif.modelo"].isin(["D", "E"])),
    (df_con_libranza["MORA12"].between(90, 180)),
]

opciones = ["A", "A", "B", "B", "C", "C", "D"]

df_con_libranza["Calif.homologada"] = np.select(condiciones, opciones, default="E")

In [43]:
df_con_libranza["Calif.homologada"].value_counts()

Calif.homologada
B    36
A    20
E     8
D     6
C     3
Name: count, dtype: int64

## Sin libranza

In [44]:
df_sin_libranza = df_all_features[
    df_all_features["CodigoContable"].isin(cod_sin_libranza)
].copy()
df_sin_libranza.info()

<class 'pandas.core.frame.DataFrame'>
Index: 3801 entries, 10 to 19697
Data columns (total 14 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   NroCredito      3801 non-null   object
 1   NIT             3801 non-null   object
 2   CodigoContable  3801 non-null   float64
 3   SALPRES         3801 non-null   float64
 4   VEA             3801 non-null   float64
 5   MORA12          3801 non-null   float64
 6   SINMORA         3801 non-null   int64
 7   Morosidad       3801 non-null   float64
 8   clasegarantia   50 non-null     float64
 9   PDI             50 non-null     float64
 10  Activo          3801 non-null   float64
 11  ANTI            3801 non-null   float64
 12  AP              3159 non-null   float64
 13  COOCDAT         5 non-null      float64
dtypes: float64(11), int64(1), object(2)
memory usage: 445.4+ KB

In [45]:
df_sin_libranza[["Activo", "ANTI", "AP"]] = df_sin_libranza[
    ["Activo", "ANTI", "AP"]
].fillna(0)
df_sin_libranza.info()

<class 'pandas.core.frame.DataFrame'>
Index: 3801 entries, 10 to 19697
Data columns (total 14 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   NroCredito      3801 non-null   object
 1   NIT             3801 non-null   object
 2   CodigoContable  3801 non-null   float64
 3   SALPRES         3801 non-null   float64
 4   VEA             3801 non-null   float64
 5   MORA12          3801 non-null   float64
 6   SINMORA         3801 non-null   int64
 7   Morosidad       3801 non-null   float64
 8   clasegarantia   50 non-null     float64
 9   PDI             50 non-null     float64
 10  Activo          3801 non-null   float64
 11  ANTI            3801 non-null   float64
 12  AP              3801 non-null   float64
 13  COOCDAT         5 non-null      float64
dtypes: float64(11), int64(1), object(2)
memory usage: 445.4+ KB

In [46]:
vars_sin_libranza = ["Activo", "ANTI", "SALPRES", "AP", "MORA12"]

lgbm_model_sin_libranza = joblib.load(models_dir / "lightgbm_sin_libranza.joblib")
df_sin_libranza["Calif.modelo"] = lgbm_model_sin_libranza.predict(
    df_sin_libranza[vars_sin_libranza]
)
df_sin_libranza

c:\Users\jhquiza\repos\proyecto-riesgos\.venv\Lib\site-packages\sklearn\base.py:442: InconsistentVersionWarning: Trying to unpickle estimator DecisionTreeClassifier from version 1.8.0 when using version 1.7.2. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:
https://scikit-learn.org/stable/model_persistence.html#security-maintainability-limitations
  warnings.warn(

,NroCredito,NIT,CodigoContable,SALPRES,VEA,MORA12,SINMORA,Morosidad,clasegarantia,PDI,Activo,ANTI,AP,COOCDAT,Calif.modelo
10,002-002-0013891-9,43801451,141220.0,0.264425,5354369.0,217.0,0,143.0,3.0,0.50,0.0,0.0,0.0,NaN,4
11,002-002-0048982-5,16224395,141225.0,0.310797,20012765.0,3886.0,0,3886.0,NaN,NaN,0.0,0.0,0.0,NaN,4
12,002-002-0054500-6,70130524,144225.0,0.912728,18820457.0,3650.0,0,3650.0,NaN,NaN,0.0,0.0,0.0,NaN,4
14,002-002-0067978-1,71338874,144225.0,0.717959,7107791.0,4053.0,0,4053.0,NaN,NaN,1.0,6760.0,3146429.0,NaN,2
15,002-002-0071402-9,98716118,144225.0,0.080658,2777408.0,685.0,0,685.0,NaN,NaN,0.0,0.0,0.0,NaN,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19680,007-002-0001399-1,1017235775,144225.0,0.857560,18557448.0,674.0,0,674.0,NaN,NaN,1.0,2993.0,1884555.0,NaN,2
19682,007-002-0001408-0,1020817982,144225.0,0.952812,4148730.0,674.0,0,674.0,1.0,1.00,1.0,847.0,360001.0,NaN,2
19683,007-002-0001413-3,80256160,144225.0,0.991802,6445153.0,674.0,0,674.0,1.0,1.00,1.0,806.0,150001.0,NaN,2
19690,007-002-0001440-0,1036610847,144210.0,0.932549,19283059.0,42.0,0,42.0,1.0,0.45,1.0,2233.0,15296133.0,NaN,1
19697,007-002-0001457-0,1007306124,144225.0,0.795854,1666621.0,104.0,0,104.0,1.0,0.60,1.0,540.0,304001.0,NaN,2

In [47]:
df_sin_libranza["Calif.modelo"] = df_sin_libranza["Calif.modelo"].map(
    {0: "A", 1: "B", 2: "C", 3: "D", 4: "E"}
)

In [48]:
condiciones = [
    (df_sin_libranza["Calif.modelo"] == "A"),
    (df_sin_libranza["Calif.modelo"] == "B") & (df_sin_libranza["MORA12"] <= 30),
    (df_sin_libranza["Calif.modelo"] == "B")
    & (df_sin_libranza["MORA12"] > 30)
    & (df_sin_libranza["MORA12"] < 90),
    (df_sin_libranza["Calif.modelo"] == "C") & (df_sin_libranza["MORA12"] <= 30),
    (df_sin_libranza["Calif.modelo"] == "C")
    & (df_sin_libranza["MORA12"] > 30)
    & (df_sin_libranza["MORA12"] < 90),
    (df_sin_libranza["Calif.modelo"].isin(["D", "E"])),
    (df_sin_libranza["MORA12"].between(90, 180)),
]

opciones = ["A", "A", "B", "B", "C", "C", "D"]

df_sin_libranza["Calif.homologada"] = np.select(condiciones, opciones, default="E")

In [49]:
df_sin_libranza["Calif.modelo"].value_counts()

Calif.modelo
C    2979
E     635
B     154
A      28
D       5
Name: count, dtype: int64

In [50]:
df_sin_libranza["Calif.homologada"].value_counts()

Calif.homologada
E    2537
C     785
D     297
B     154
A      28
Name: count, dtype: int64

## Calificación de arrastre, calificación final y cálculo de PI y PE

In [51]:
# Crear un dataframe que tenga una columna que seea el NIT de los dataframes df_con_libranza y df_sin_libranza y
# otra columna que sea la peor calificacion homologada de cada NIT

df_peor_calificacion = pd.concat(
    [
        df_con_libranza[["NIT", "Calif.homologada"]],
        df_sin_libranza[["NIT", "Calif.homologada"]],
    ]
)
df_peor_calificacion = (
    df_peor_calificacion.groupby("NIT")["Calif.homologada"].max().reset_index()
)
df_peor_calificacion

                NIT Calif.homologada
0            366107                E
1            487714                E
2            523105                D
3            530518                B
4            549325                E
...             ...              ...
3478     1238339472                E
3479     1238938019                E
3480     1239488421                E
3481     2000012422                D
3482  900-937-066-2                E

[3483 rows x 2 columns]

In [52]:
# En df_con_libranza crear una columna llamada 'Calif.final' cuyos valores sean iguales a la columna 'Calif.homologada' del df_peor_calificacion de acuerdo al valor de NIT.
df_con_libranza["Calif.final"] = df_con_libranza["NIT"].map(
    df_peor_calificacion.set_index("NIT")["Calif.homologada"]
)
df_con_libranza["Calif.final"].value_counts()

Calif.final
B    43
E    13
D    12
C     5
Name: count, dtype: int64

In [53]:
# En df_sin_libranza crear una columna llamada 'Calif.final' cuyos valores sean iguales a la columna 'Calif.homologada' del df_peor_calificacion de acuerdo al valor de NIT.
df_sin_libranza["Calif.final"] = df_sin_libranza["NIT"].map(
    df_peor_calificacion.set_index("NIT")["Calif.homologada"]
)
df_sin_libranza["Calif.final"].value_counts()

Calif.final
E    2563
C     782
D     300
B     156
Name: count, dtype: int64

In [54]:
# Crear una columna llamada 'PI' aue se calcula así: si calificación es A, PI = 0.005;
# si calificación es B, PI = 0.006; si calificación es C, PI = 0.0441;
# si calificación es D, PI = 0.0448; si calificación es E, PI = 0.2273
df_con_libranza["PI"] = df_con_libranza["Calif.final"].map(
    {"A": 0.005, "B": 0.006, "C": 0.0441, "D": 0.0448, "E": 0.2273}
)

df_con_libranza["PI"] = df_con_libranza["PI"].astype(float)

df_con_libranza["PE"] = (
    df_con_libranza["PI"] * df_con_libranza["VEA"] * df_con_libranza["PDI"]
)

df_con_libranza

,NroCredito,NIT,CodigoContable,SALPRES,VEA,MORA12,SINMORA,Morosidad,clasegarantia,PDI,Activo,ANTI,AP,COOCDAT,Calif.modelo,Calif.homologada,Calif.final,PI,PE
409,002-002-0119592-6,15508251,141110.0,0.001944,23179.0,33.0,0,33.0,NaN,NaN,1.0,9982.0,6630767.0,0.0,B,B,B,0.0060,NaN
478,002-002-0120768-2,43557644,144125.0,0.454133,19608451.0,0.0,1,0.0,NaN,NaN,1.0,3254.0,6480001.0,0.0,A,A,E,0.2273,NaN
788,002-002-0125077-7,42789870,141110.0,0.005368,54339.0,41.0,0,41.0,NaN,NaN,1.0,2321.0,3035205.0,0.0,B,B,B,0.0060,NaN
1233,002-002-0128853-1,8461117,144125.0,0.537680,10846461.0,0.0,1,0.0,NaN,NaN,1.0,4411.0,1584877.0,0.0,A,A,E,0.2273,NaN
1263,002-002-0129255-3,1039623661,144110.0,0.696457,18689349.0,31.0,0,31.0,NaN,NaN,1.0,3619.0,1664223.0,0.0,B,B,B,0.0060,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17584,006-002-0032251-9,1045735821,144120.0,0.852780,11246995.0,0.0,1,0.0,NaN,NaN,1.0,3332.0,671327.0,0.0,A,A,D,0.0448,NaN
17722,006-002-0032804-1,1007321384,144125.0,0.612451,1855660.0,0.0,1,0.0,NaN,NaN,1.0,882.0,799132.0,0.0,A,A,E,0.2273,NaN
17886,006-002-0033378-5,43989143,144110.0,0.412673,1255057.0,0.0,1,0.0,NaN,NaN,1.0,1124.0,1063201.0,0.0,A,A,B,0.0060,NaN
18356,006-002-0034788-7,70567161,144110.0,0.704429,1839090.0,42.0,0,42.0,NaN,NaN,1.0,2128.0,1750460.0,0.0,B,B,B,0.0060,NaN
18405,006-002-0034901-9,1033340571,144110.0,0.612033,1908791.0,93.0,0,33.0,NaN,NaN,1.0,284.0,258533.0,0.0,C,D,D,0.0448,NaN

In [55]:
# Crear una columna llamada 'PI' aue se calcula así: si calificación es A, PI = 0.005;
# si calificación es B, PI = 0.006; si calificación es C, PI = 0.0441;
# si calificación es D, PI = 0.0448; si calificación es E, PI = 0.2273
df_sin_libranza["PI"] = df_sin_libranza["Calif.final"].map(
    {"A": 0.015, "B": 0.0595, "C": 0.1382, "D": 0.3277, "E": 0.4171}
)

df_sin_libranza["PI"] = df_sin_libranza["PI"].astype(float)

df_sin_libranza["PE"] = (
    df_sin_libranza["PI"] * df_sin_libranza["VEA"] * df_sin_libranza["PDI"]
)

df_sin_libranza

,NroCredito,NIT,CodigoContable,SALPRES,VEA,MORA12,SINMORA,Morosidad,clasegarantia,PDI,Activo,ANTI,AP,COOCDAT,Calif.modelo,Calif.homologada,Calif.final,PI,PE
10,002-002-0013891-9,43801451,141220.0,0.264425,5354369.0,217.0,0,143.0,3.0,0.50,0.0,0.0,0.0,NaN,E,C,C,0.1382,3.699869e+05
11,002-002-0048982-5,16224395,141225.0,0.310797,20012765.0,3886.0,0,3886.0,NaN,NaN,0.0,0.0,0.0,NaN,E,C,C,0.1382,NaN
12,002-002-0054500-6,70130524,144225.0,0.912728,18820457.0,3650.0,0,3650.0,NaN,NaN,0.0,0.0,0.0,NaN,E,C,C,0.1382,NaN
14,002-002-0067978-1,71338874,144225.0,0.717959,7107791.0,4053.0,0,4053.0,NaN,NaN,1.0,6760.0,3146429.0,NaN,C,E,E,0.4171,NaN
15,002-002-0071402-9,98716118,144225.0,0.080658,2777408.0,685.0,0,685.0,NaN,NaN,0.0,0.0,0.0,NaN,E,C,C,0.1382,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19680,007-002-0001399-1,1017235775,144225.0,0.857560,18557448.0,674.0,0,674.0,NaN,NaN,1.0,2993.0,1884555.0,NaN,C,E,E,0.4171,NaN
19682,007-002-0001408-0,1020817982,144225.0,0.952812,4148730.0,674.0,0,674.0,1.0,1.00,1.0,847.0,360001.0,NaN,C,E,E,0.4171,1.730435e+06
19683,007-002-0001413-3,80256160,144225.0,0.991802,6445153.0,674.0,0,674.0,1.0,1.00,1.0,806.0,150001.0,NaN,C,E,E,0.4171,2.688273e+06
19690,007-002-0001440-0,1036610847,144210.0,0.932549,19283059.0,42.0,0,42.0,1.0,0.45,1.0,2233.0,15296133.0,NaN,B,B,B,0.0595,5.163039e+05
19697,007-002-0001457-0,1007306124,144225.0,0.795854,1666621.0,104.0,0,104.0,1.0,0.60,1.0,540.0,304001.0,NaN,C,D,E,0.4171,4.170886e+05

# Se guardan estimaciones

In [56]:
# Guardar en archivo csv llamado 'df_con_libranza_calificaciones_septiembre_2025.csv' el dataframe df_con_libranza
df_con_libranza.to_csv(
    data_dir / f"df_con_libranza_calificaciones_{mes_anno}.csv", index=False
)

In [57]:
# Guardar en archivo csv llamado 'df_sin_libranza_calificaciones_septiembre_2025.csv' el dataframe df_sin_libranza
df_sin_libranza.to_csv(
    data_dir / f"df_sin_libranza_calificaciones_{mes_anno}.csv", index=False
)