In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("Datos_2013_2025_cooperativas.csv")
df.sample(5)

,CUENTA,NOMBRE CUENTA,COOPERATIVA DE EMPLEADOS DE CAFAM,COOPERATIVA DE TRABAJADORES DE LA INDUSTRIA MILITAR,COOPERATIVA DE LOS PROFESIONALES DE LA SALUD COASMEDAS,COOPERATIVA DE AHORRO Y CREDITO PARA EL BIENESTAR SOCIAL,COOPERATIVA PARA EL BIENESTAR SOCIAL,COOPERATIVA FINANCIERA SAN FRANCISCO,COOPERATIVA MULTIACTIVA DE LA AVIACION CIVIL COLOMBIANA,COOPERATIVA DE EMPLEADOS DE DOW COLOMBIA,...,COOPERATIVA DE AHORRO Y CREDITO INTEGRAR,COOPERATIVA MULTIACTIVA DE APORTE Y CREDITO,MICROEMPRESAS DE ANTIOQUIA COOPERATIVA DE AHORRO Y CREDITO,COOPERATIVA ESPECIALIZADA DE AHORRO Y CREDITO CANAPRO,COOPERATIVA MULTIACTIVA UNION DE COMERCIANTES PLAZA TRINIDAD GALAN,FONDO DE EMPLEADOS DEL MINISTERIO DEL INTERIOR,COOPERATIVA AVANZA,COOPERATIVA MULTIACTIVA UNION COLOMBIANA,PRECOOPERATIVA PARA EL FOMENTO Y DESARROLLO DE LAS ACTIVIDADES MINERAS,fecha
225867,190520,COMISIONES,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2021-05-01
166836,282000,"PROVISIÓN MULTAS, SANCIONES, LITIGIOS, INDEMNI...",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2022-01-01
156579,276015,ANTICIPOS SOBRE CONVENIOS Y ACUERDOS,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2021-02-01
74187,112015,FONDOS ESPECIALES - FONDOS SOCIALES Y MUTUALES,0.0,NaN,0.0,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2026-01-01
184765,161005,VIGENTES,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2019-05-01

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 320602 entries, 0 to 320601
Columns: 290 entries, CUENTA to fecha
dtypes: float64(287), int64(1), object(2)
memory usage: 709.3+ MB

In [6]:
df_fecha = df[["fecha"]]
df_fecha.sample(5)

             fecha
13237   2023-05-01
290159  2013-01-01
91245   2015-04-01
105362  2015-02-01
190112  2021-05-01

In [7]:
df_fecha["fecha"] = pd.to_datetime(df_fecha["fecha"], format="%Y-%m-%d")
df_fecha.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 320602 entries, 0 to 320601
Data columns (total 1 columns):
 #   Column  Non-Null Count   Dtype
---  ------  --------------   -----
 0   fecha   320602 non-null  datetime64[ns]
dtypes: datetime64[ns](1)
memory usage: 2.4 MB

C:\Users\jhquiza\AppData\Local\Temp\ipykernel_9116\3601168384.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_fecha["fecha"] = pd.to_datetime(df_fecha["fecha"], format="%Y-%m-%d")

In [8]:
df_fecha.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 320602 entries, 0 to 320601
Data columns (total 1 columns):
 #   Column  Non-Null Count   Dtype
---  ------  --------------   -----
 0   fecha   320602 non-null  datetime64[ns]
dtypes: datetime64[ns](1)
memory usage: 2.4 MB

In [9]:
df_fecha["mes"] = df_fecha["fecha"].dt.month
df_fecha["año"] = df_fecha["fecha"].dt.year
df_fecha.sample(5)

C:\Users\jhquiza\AppData\Local\Temp\ipykernel_9116\2135008408.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_fecha["mes"] = df_fecha["fecha"].dt.month
C:\Users\jhquiza\AppData\Local\Temp\ipykernel_9116\2135008408.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_fecha["año"] = df_fecha["fecha"].dt.year

            fecha  mes   año
231666 2017-05-01    5  2017
272536 2013-04-01    4  2013
307350 2013-08-01    8  2013
41910  2024-05-01    5  2024
215195 2022-03-01    3  2022

In [11]:
df_fecha['mes'].value_counts().sort_values(ascending=False)

mes
5     159268
2      43989
1      38940
3      38029
4      28295
6       2879
9       2879
8       2879
10      2879
7        565
Name: count, dtype: int64

In [18]:
df_fecha["año"].value_counts()

año
2013    33669
2025    27359
2017    26427
2024    25732
2023    25414
2021    25040
2022    25036
2020    24743
2019    24360
2018    24288
2014    20613
2015    16834
2016    13977
2026     7110
Name: count, dtype: int64

In [20]:
df_fecha[df_fecha["mes"] == 7]["año"].value_counts()

año
2013    565
Name: count, dtype: int64

In [21]:
df_fecha[df_fecha["mes"] == 6]["año"].value_counts()

año
2013    2879
Name: count, dtype: int64

In [22]:
df_fecha[df_fecha["mes"] == 8]["año"].value_counts()

año
2013    2879
Name: count, dtype: int64

In [25]:
df_fecha[df_fecha["mes"] == 5]["año"].value_counts()

año
2017    18331
2024    17247
2018    16192
2020    14488
2025    13050
2023    12785
2021    12519
2022    12518
2019    12180
2014    11800
2015     9900
2016     5379
2013     2879
Name: count, dtype: int64

In [26]:
df_fecha[df_fecha["mes"] == 2]["año"].value_counts()

año
2022    6259
2014    4671
2016    4301
2021    4174
2019    4066
2013    2879
2015    2777
2026    2390
2025    2180
2024    2110
2023    2092
2020    2042
2018    2024
2017    2024
Name: count, dtype: int64

In [27]:
df_fecha[df_fecha["mes"] == 3]["año"].value_counts()

año
2023    6359
2025    5589
2013    4314
2026    2385
2016    2173
2024    2149
2022    2087
2021    2087
2020    2042
2017    2024
2018    2024
2019    2024
2014    1389
2015    1383
Name: count, dtype: int64

In [2]:
# Cargar primeras filas del archivo Excel

df = pd.read_excel(
    "20241009_estados_financieros_ahorro_credito_agosto24.xlsx",
    skiprows=1,
    nrows=5,
    )

df.head()

ImportError: Missing optional dependency 'openpyxl'.  Use pip or conda to install openpyxl.